# Generated by Django 5.2.5 on 2025-08-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom d'appel d'offre")),
                ('objet', models.TextField(max_length=200, verbose_name='Objet du marché')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Numéro du marché')),
                ('maitre_ouvrage', models.CharField(max_length=200, verbose_name="Maître d'ouvrage")),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
                ('type', models.CharField(choices=[('TRAVAUX', 'Travaux'), ('FOURNITURES', 'Fournitures'), ('SERVICES', 'Services'), ('CONCESSION', 'Concession'), ('PARTENARIAT', 'Partenariat'), ('AUTRE', 'Autre')], default='TRAVAUX', max_length=20, verbose_name="Type d'AO")),
                ('date_reception', models.DateField(verbose_name="Date d'appel d'offres")),
                ('date_limite', models.DateField(verbose_name='Date limite de soumission')),
                ('estimation_moa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimation du MOA (DH)')),
                ('caution_provisoire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Caution provisoire (DH)')),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='Décision')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('avancement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Avancement (%)')),
            ],
            options={
                'verbose_name': "Appel d'offre",
                'verbose_name_plural': "Appels d'offre",
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(blank=True, choices=[('VRD', 'Voirie et Réseaux Divers'), ('ROUTE', 'Route'), ('PONT', 'Pont'), ('BATIMENT', 'Bâtiment'), ('CONSTRUCTION', 'Construction'), ('ASSAINISSEMENT EP', 'Assainissement EP'), ('ASSAINISSEMENT EU', 'Assainissement EU'), ('ASSAINISSEMENT', 'Assainissement'), ('ADDUCTION_EAU_POTABLE', "Adduction d'eau potable"), ('EQUIPEMENT', 'Équipement'), ('AMENAGEMENT', 'Aménagement'), ('GENIE_CIVIL', 'Génie Civil'), ('TRAVAUX_PUBLICS', 'Travaux Publics'), ('ELECTRICITE', 'Électricité'), ('HYDRAULIQUE', 'Hydraulique'), ('TELECOMMUNICATION', 'Télécommunication'), ('ENVIRONNEMENT', 'Environnement'), ('URBANISME', 'Urbanisme'), ('AUTRE', 'Autre')], default='VRD', max_length=50, null=True, verbose_name='Type de projet')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du projet')),
                ('objet', models.TextField(max_length=200, verbose_name='Objet du marché')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Numéro du marché')),
                ('maitre_ouvrage', models.CharField(max_length=200, verbose_name="Maître d'ouvrage")),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant estimé (DH)')),
                ('montant_soumission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant de la soumission (DH)')),
                ('statut', models.CharField(choices=[('AO', "Appel d'offre"), ('ETUDE', 'En étude'), ('ATTENTE', 'En attente'), ('DEM', 'En démarrage'), ('COURS', 'En cours'), ('ARRET', 'En arrêt'), ('RECEP', 'En réception'), ('RECEP_PROV', 'En réception provisoire'), ('RECEP_DEF', 'En réception définitive'), ('RP', 'Réception provisoire'), ('RD', 'Réception définitive'), ('CLO', 'Clôturé')], default='AO', max_length=15, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('delai', models.IntegerField(blank=True, default=0, null=True, verbose_name='Délai (jours)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('avancement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Avancement (%)')),
                ('a_traiter', models.BooleanField(blank=True, default=False, null=True, verbose_name="À traiter (appel d'offre)")),
                ('en_retard', models.BooleanField(blank=True, default=False, null=True, verbose_name='En retard')),
                ('reception_validee', models.BooleanField(blank=True, default=False, null=True, verbose_name='Réception validée')),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date de réception')),
                ('date_limite_soumission', models.DateField(blank=True, null=True, verbose_name='Date limite de soumission')),
                ('appel_offre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_associe', to='projets.appeloffre')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projets.entreprise', verbose_name='Entreprise adjudicataire')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='projet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appel_offre_rel', to='projets.projet'),
        ),
    ]
