# Generated by Django 5.2.5 on 2025-08-13 15:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents_administratifs/', verbose_name='Fichier')),
                ('type_document', models.CharField(max_length=100, verbose_name='Type de document')),
                ('date_remise', models.DateField(blank=True, null=True, verbose_name='Date de remise')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_administratifs', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Document administratif',
                'verbose_name_plural': 'Documents administratifs',
                'ordering': ['type_document'],
            },
        ),
        migrations.CreateModel(
            name='LotProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du lot')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Lot du projet',
                'verbose_name_plural': 'Lots du projet',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneBordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='N°')),
                ('designation', models.TextField(verbose_name='Désignation')),
                ('unite', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unité')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (DH)')),
                ('montant_calcule', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='projets.lignebordereau', verbose_name='Ligne parente (optionnel)')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='projets.lotprojet', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Ligne de bordereau',
                'verbose_name_plural': 'Lignes de bordereau',
            },
        ),
        migrations.CreateModel(
            name='OrdreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_publication', models.DateField()),
                ('date_limite', models.DateField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='ordres_services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projets.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('terminee', models.BooleanField(default=False)),
                ('avancement', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['date_fin'],
            },
        ),
    ]
