# Generated by Django 5.2.5 on 2025-08-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Ingenieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
