# Generated by Django 5.2.5 on 2025-08-14 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_client_ingenieur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de suivi')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_suivi', models.CharField(choices=[('reunion', 'Réunion de chantier'), ('incident', 'Incident'), ('planning', 'Mise à jour planning'), ('autre', 'Autre')], max_length=100, verbose_name='Type')),
                ('commentaire', models.TextField(verbose_name='Commentaire ou résumé')),
                ('redacteur', models.CharField(blank=True, max_length=100, verbose_name='Rédigé par : ')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_execution', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Suivi d’exécution',
                'verbose_name_plural': 'Suivis d’exécution',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FichierSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='suivis_execution/', verbose_name='Fichier')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='projets.suiviexecution', verbose_name='Suivi')),
            ],
            options={
                'verbose_name': 'Fichier joint au suivi',
                'verbose_name_plural': 'Fichiers joints au suivi',
                'ordering': ['id'],
            },
        ),
    ]
