# Generated by Django 5.2.4 on 2025-08-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_suiviexecution_fichiersuivi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', help_text='Upload a profile picture (300x300 recommended)', upload_to='avatars/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type_projet',
            field=models.CharField(blank=True, choices=[('VRD', 'Voirie et Réseaux Divers'), ('ROUTE', 'Route'), ('PONT', 'Pont'), ('BATIMENT', 'Bâtiment'), ('CONSTRUCTION', 'Construction'), ('ASSAINISSEMENT EP', 'Assainissement EP'), ('ASSAINISSEMENT EU', 'Assainissement EU'), ('ASSAINISSEMENT', 'Assainissement'), ('ADDUCTION_EAU_POTABLE', "Adduction d'eau potable"), ('EQUIPEMENT', 'Équipement'), ('AMENAGEMENT', 'Aménagement'), ('GENIE_CIVIL', 'Génie Civil'), ('TRAVAUX_PUBLICS', 'Travaux Publics'), ('ELECTRICITE', 'Électricité'), ('HYDRAULIQUE', 'Hydraulique'), ('TELECOMMUNICATION', 'Télécommunication'), ('ENVIRONNEMENT', 'Environnement'), ('URBANISME', 'Urbanisme'), ('ESPACE_PUBLIC', 'Espace Public'), ('PLACE_PUBLIQUE', 'Place Publique'), ('ESPACE_VERT', 'Espace Vert'), ('TERRAINS_SPORTIFS', 'Terrins Sportifs'), ('TERRAINS_PROXIMITES', 'Terrains Proximités'), ('AUTRE', 'Autre')], default='VRD', max_length=50, null=True, verbose_name='Type de projet'),
        ),
    ]
