# Generated by Django 5.2.4 on 2025-08-20 12:37

import projets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to=projets.models.avatar_upload_path),
        ),
    ]
