# Generated by Django 5.2.4 on 2025-09-15 17:36

import django.utils.timezone
import projets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichiersuivi',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Fichier joint au suivi', 'verbose_name_plural': 'Fichiers joints au suivi'},
        ),
        migrations.AlterModelOptions(
            name='suiviexecution',
            options={'ordering': ['-date', '-date_creation'], 'verbose_name': "Suivi d'exécution", 'verbose_name_plural': "Suivis d'exécution"},
        ),
        migrations.AddField(
            model_name='fichiersuivi',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout"),
        ),
        migrations.AddField(
            model_name='suiviexecution',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='suiviexecution',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='suiviexecution',
            name='importance',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée')], default='moyenne', max_length=10, verbose_name='Importance'),
        ),
        migrations.AlterField(
            model_name='documentadministratif',
            name='fichier',
            field=models.FileField(upload_to=projets.models.document_upload_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='fichiersuivi',
            name='fichier',
            field=models.FileField(upload_to=projets.models.FichierSuivi.upload_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='suiviexecution',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de suivi'),
        ),
        migrations.AlterField(
            model_name='suiviexecution',
            name='redacteur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rédigé par'),
        ),
        migrations.AlterField(
            model_name='suiviexecution',
            name='type_suivi',
            field=models.CharField(choices=[('reunion', 'Réunion de chantier'), ('incident', 'Incident'), ('planning', 'Mise à jour planning'), ('livraison', 'Livraison'), ('validation', "Validation d'étape"), ('autre', 'Autre')], max_length=100, verbose_name='Type'),
        ),
    ]
