# Generated by Django 5.2.4 on 2025-09-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0010_alter_fichiersuivi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name="Numéro d'attachement")),
                ('date_etablissement', models.DateField(verbose_name="Date d'établissement")),
                ('date_debut_periode', models.DateField(verbose_name='Date début période')),
                ('date_fin_periode', models.DateField(verbose_name='Date fin période')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SIGNE', 'Signé'), ('TRANSMIS', 'Transmis'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=15)),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='attachements/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachements', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Attachement',
                'verbose_name_plural': 'Attachements',
                'ordering': ['-date_etablissement', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='Decompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_decompte', models.CharField(choices=[('PROVISOIRE', 'Décompte provisoire'), ('DEFINITIF', 'Décompte définitif'), ('SOLDE', 'Décompte de solde')], default='PROVISOIRE', max_length=15)),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de décompte')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMIS', 'Émis'), ('EN_RETARD', 'En retard de paiement'), ('PAYE', 'Payé'), ('PARTIEL', 'Payé partiellement')], default='BROUILLON', max_length=15)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TTC')),
                ('taux_retenue_garantie', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taux retenue de garantie (%)')),
                ('montant_retenue_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant retenue de garantie')),
                ('taux_ras', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux RAS (%)')),
                ('montant_ras', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant RAS')),
                ('autres_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Autres retenues')),
                ('montant_net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant net à payer')),
                ('numero_bordereau', models.CharField(blank=True, max_length=50, verbose_name='Numéro de bordereau')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('attachement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decompte', to='projets.attachement')),
            ],
            options={
                'verbose_name': 'Décompte',
                'verbose_name_plural': 'Décomptes',
                'ordering': ['-date_emission', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LigneAttachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_realisee', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantité réalisée')),
                ('quantite_cumulee', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantité cumulée')),
                ('attachement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_attachement', to='projets.attachement')),
                ('ligne_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_attachement', to='projets.lignebordereau')),
            ],
            options={
                'verbose_name': "Ligne d'attachement",
                'verbose_name_plural': "Lignes d'attachement",
                'unique_together': {('attachement', 'ligne_lot')},
            },
        ),
    ]
