# Generated by Django 5.2.4 on 2025-09-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0011_attachement_decompte_ligneattachement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneattachement',
            name='designation',
            field=models.TextField(default='Designation', verbose_name='Désignation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneattachement',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N°'),
        ),
        migrations.AddField(
            model_name='ligneattachement',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DH)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneattachement',
            name='quantite_initiale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligneattachement',
            name='unite',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unité'),
        ),
    ]
