# Generated by Django 5.2.4 on 2025-10-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0012_ligneattachement_designation_ligneattachement_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordreservice',
            options={'ordering': ['projet', 'ordre_sequence', 'date_publication']},
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='date_effet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='duree_extension',
            field=models.IntegerField(blank=True, help_text="Durée d'extension en jours", null=True),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='montant_supplementaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='ordre_sequence',
            field=models.IntegerField(default=1, help_text='Ordre dans la séquence du projet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('NOTIFIE', 'Notifié'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projets.projet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ordreservice',
            unique_together={('projet', 'reference')},
        ),
        migrations.CreateModel(
            name='TypeOrdreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('OSN', "OS de Notification de l'approbation du marché"), ('OSC', 'OS de Commencement'), ('OSA', "OS d'Arrêt"), ('OSR', 'OS de Reprise'), ('OSC10', "OS de Continuation jusqu'à 10%"), ('OSA', "OS d'Approbation d'Avenant"), ('AUTRE', 'Autre OS')], max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordre_min', models.IntegerField(help_text='Ordre minimum dans la séquence')),
                ('ordre_max', models.IntegerField(help_text='Ordre maximum dans la séquence')),
                ('unique_dans_projet', models.BooleanField(default=False)),
                ('precedent_obligatoire', models.ManyToManyField(blank=True, to='projets.typeordreservice')),
            ],
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='type_os',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projets.typeordreservice'),
            preserve_default=False,
        ),
    ]
