# Generated by Django 5.2.4 on 2025-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0013_alter_ordreservice_options_ordreservice_date_effet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('RETARD', 'Projet en retard'), ('NOUVEAU_AO', "Nouvel appel d'offres"), ('RECEPTION', 'Réception validée'), ('REUNION', 'Rendez-vous'), ('ECHEANCE', 'Échéance approchante'), ('OS_NOTIFIE', 'Ordre de service notifié'), ('OS_ANNULE', 'Ordre de service annulé'), ('OS_ECHEANCE', 'Échéance OS approchante'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
