# Generated by Django 5.2.5 on 2025-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0014_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CHEF_PROJET', 'Chef de Projet'), ('UTILISATEUR', 'Utilisateur')], default='UTILISATEUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='duree_extension',
            field=models.IntegerField(blank=True, default=0, help_text="Durée d'extension en jours", null=True),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='montant_supplementaire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='typeordreservice',
            name='code',
            field=models.CharField(choices=[('OSN', "OS de Notification de l'approbation du marché"), ('OSC', 'OS de Commencement'), ('OSA', "OS d'Arrêt"), ('OSR', 'OS de Reprise'), ('OSC10', "OS de Continuation jusqu'à 10%"), ('OSV', "OS d'Approbation d'Avenant"), ('AUTRE', 'Autre OS')], max_length=10, unique=True),
        ),
    ]
