# Generated by Django 5.2.5 on 2025-10-12 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0015_profile_role_alter_ordreservice_duree_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('EMIS', 'Émis'), ('EN_RETARD', 'En retard de paiement'), ('PAYE', 'Payé'), ('PARTIEL', 'Payé partiellement')], default='BROUILLON', max_length=15),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='taux_retenue_garantie',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux retenue de garantie (%)'),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_service', to='projets.projet'),
        ),
    ]
