# Generated by Django 5.2.4 on 2025-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0016_alter_decompte_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='epoque_base',
            field=models.DateField(blank=True, null=True, verbose_name='Epoque de base'),
        ),
        migrations.AddField(
            model_name='projet',
            name='revisable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Revisable'),
        ),
    ]
