# Generated by Django 5.2.4 on 2025-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0017_projet_epoque_base_projet_revisable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDecompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_depenses', models.CharField(choices=[('penalite_retard', 'PENALITE POUR RETARD DE TRAVAUX'), ('penalite_absence_reunion', 'PENALITES POUR ABSENCE REUNION DE CHANTIER'), ('autre_penalite', 'AUTRE PENALITE'), ('revision_prix', 'REVISION DES PRIX'), ('retenue_assurance_decenale', 'RETENUE ASSURANCE DECENALE'), ('retenue_garantie', 'RETENUE GARANTIE'), ('ras', 'RETENUE A LA SOURCE'), ('penalite_retard', 'PENALITE POUR RETARD DE TRAVAUX'), ('autres', 'AUTRES RETENUES')], max_length=50, verbose_name='Nature des dépenses')),
                ('nature_recettes', models.CharField(choices=[('travaux_metre', 'TRAVAUX TERMINES AU METRE'), ('travaux_forfait', 'TRAVAUX TERMINES AU FORFAIT'), ('travaux_avenants', 'TRAVAUX TERMINES AVENANTS'), ('travaux_non_termines', 'TRAVAUX NON TERMINES'), ('approvisionnement', 'APPROVISIONNEMENT'), ('honoraires', 'HONORAIRES')], max_length=50, verbose_name='Nature des recettes')),
                ('cumul_a_date', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Cumul à date (A)')),
                ('cumul_deja_percu', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Cumul déjà perçu (B)')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Reste à payer (A)-(B)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Décompte',
                'verbose_name_plural': 'Décomptes',
                'ordering': ['nature_depenses'],
            },
        ),
        migrations.CreateModel(
            name='ResumeDecompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Sous-total HT')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total HT')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA %')),
                ('tva_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Montant TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total TTC')),
                ('acompte_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Acompte TTC à délivrer')),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Résumé de décompte',
                'verbose_name_plural': 'Résumés de décomptes',
            },
        ),
    ]
