# Generated by Django 5.2.4 on 2025-10-25 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0018_lignedecompte_resumedecompte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_validation', models.CharField(choices=[('TECHNIQUE', 'Validation technique'), ('ADMINISTRATIVE', 'Validation administrative'), ('FINANCIERE', 'Validation financière'), ('FINAL', 'Validation finale')], default='TECHNIQUE', max_length=20, verbose_name='Type de validation')),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CORRECTION', 'En cours de correction')], default='EN_ATTENTE', max_length=15, verbose_name='Statut de la validation')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_limite', models.DateTimeField(blank=True, null=True, verbose_name='Date limite de validation')),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Commentaires sur la validation')),
                ('motifs_rejet', models.TextField(blank=True, null=True, verbose_name='Motifs de rejet le cas échéant')),
                ('fichier_validation', models.FileField(blank=True, null=True, upload_to='validations_attachements/%Y/%m/', verbose_name='Fichier de validation')),
                ('ordre_validation', models.PositiveIntegerField(default=1, verbose_name='Ordre dans le processus de validation')),
                ('est_obligatoire', models.BooleanField(default=True, verbose_name='Validation obligatoire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='projets.attachement', verbose_name='Attachement à valider')),
                ('demandeur_validation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_demandees', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur de validation')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Processus de validation',
                'verbose_name_plural': 'Processus de validation',
                'ordering': ['attachement', 'ordre_validation', 'type_validation'],
                'indexes': [models.Index(fields=['attachement', 'statut_validation'], name='projets_pro_attache_a8e27c_idx'), models.Index(fields=['validateur', 'statut_validation'], name='projets_pro_validat_4fe7a7_idx'), models.Index(fields=['date_limite'], name='projets_pro_date_li_e5997a_idx')],
                'unique_together': {('attachement', 'type_validation')},
            },
        ),
    ]
