# Generated by Django 5.2.4 on 2025-10-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0019_processvalidation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignebordereau',
            options={'ordering': ['ordre_affichage', 'id'], 'verbose_name': 'Ligne de bordereau', 'verbose_name_plural': 'Lignes de bordereau'},
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='est_titre',
            field=models.BooleanField(default=False, verbose_name='Est un titre'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='niveau',
            field=models.IntegerField(default=0, verbose_name='Niveau hiérarchique'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='ordre_affichage',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
    ]
