# Generated by Django 5.2.4 on 2025-10-28 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0020_alter_lignebordereau_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField()),
                ('est_validee', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('obligatoire', models.BooleanField(default=True)),
                ('processValidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='projets.processvalidation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étape de validation',
                'verbose_name_plural': 'Étapes de validation',
                'ordering': ['ordre'],
            },
        ),
    ]
