# Generated by Django 5.2.5 on 2025-11-23 23:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0021_etapevalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='fichier',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='documentadministratif',
            name='fichier',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='fichiersuivi',
            name='fichier',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='processvalidation',
            name='fichier_validation',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/default_avatar', max_length=255, verbose_name='image'),
        ),
    ]
