# Generated by Django 5.2.5 on 2025-11-26 11:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0023_projet_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachement',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/defult.png', max_length=255, verbose_name='image'),
        ),
    ]
