# Generated by Django 5.2.5 on 2025-11-30 23:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0024_attachement_original_filename_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapevalidation',
            name='fichier_validation',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
