# Generated by Django 5.2.5 on 2025-12-01 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0025_etapevalidation_fichier_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_lue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='niveau_urgence',
            field=models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('RETARD', 'Projet en retard'), ('NOUVEAU_AO', "Nouvel appel d'offres"), ('RECEPTION', 'Réception validée'), ('REUNION', 'Rendez-vous'), ('ECHEANCE', 'Échéance approchante'), ('OS_NOTIFIE', 'Ordre de service notifié'), ('OS_ANNULE', 'Ordre de service annulé'), ('OS_ECHEANCE', 'Échéance OS approchante'), ('VALIDATION_ATTACHEMENT', 'Validation attachement requise'), ('ETAPE_VALIDEE', 'Étape de validation terminée'), ('DOCUMENT_A_SIGNER', 'Document à signer'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'lue'], name='projets_not_utilisa_274adb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date_creation'], name='projets_not_date_cr_92b0d1_idx'),
        ),
    ]
