# Generated by Django 5.2.5 on 2025-12-01 11:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0026_alter_notification_options_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapevalidation',
            name='fichier_validation',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='fichier_validation', max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.RenameField(
            model_name='etapevalidation',
            old_name='fichier_validation',
            new_name='fichier',
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='documents', max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.RenameField(
            model_name='ordreservice',
            old_name='documents',
            new_name='fichier',
        ),
        migrations.AddField(
            model_name='documentadministratif',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
        migrations.AddField(
            model_name='etapevalidation',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
        migrations.AddField(
            model_name='fichiersuivi',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
        migrations.AddField(
            model_name='ordreservice',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
    ]
