# Generated by Django 5.2.5 on 2025-12-01 11:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0027_alter_etapevalidation_fichier_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processvalidation',
            name='fichier_validation',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='fichier_validation', max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.RenameField(
            model_name='processvalidation',
            old_name='fichier_validation',
            new_name='fichier',
        ),
        migrations.AddField(
            model_name='processvalidation',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
    ]
