# Generated by Django 5.2.5 on 2025-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0028_alter_processvalidation_fichier_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentadministratif',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
