# Generated by Django 5.2.5 on 2025-12-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0029_documentadministratif_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-prioritaire', '-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='can_be_closed',
            field=models.BooleanField(default=True, help_text="L'utilisateur peut fermer cette notification"),
        ),
        migrations.AddField(
            model_name='notification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projets.documentadministratif'),
        ),
        migrations.AddField(
            model_name='notification',
            name='emetteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Émetteur de la notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expire_le',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de la notification", null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='objet_id',
            field=models.PositiveIntegerField(blank=True, help_text="ID de l'objet concerné", null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='objet_type',
            field=models.CharField(blank=True, help_text="Type d'objet (ex: 'tache', 'document', 'reunion')", max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='ordre_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projets.ordreservice'),
        ),
        migrations.AddField(
            model_name='notification',
            name='prioritaire',
            field=models.BooleanField(default=False, help_text="Notification prioritaire (s'affiche en premier)"),
        ),
        migrations.AddField(
            model_name='notification',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projets.tache'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='niveau_urgence',
            field=models.CharField(choices=[('INFO', 'Information'), ('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOUVELLE_TACHE', 'Nouvelle tâche créée'), ('TACHE_ASSIGNEE', 'Tâche assignée'), ('TACHE_MODIFIEE', 'Tâche modifiée'), ('TACHE_TERMINEE', 'Tâche terminée'), ('TACHE_URGENTE', 'Tâche devenue urgente'), ('TACHE_ECHEANCE', 'Échéance tâche approchante'), ('TACHE_EN_RETARD', 'Tâche en retard'), ('RETARD', 'Projet en retard'), ('NOUVEAU_AO', "Nouvel appel d'offres"), ('RECEPTION', 'Réception validée'), ('REUNION', 'Rendez-vous'), ('ECHEANCE', 'Échéance approchante'), ('OS_NOTIFIE', 'Ordre de service notifié'), ('OS_ANNULE', 'Ordre de service annulé'), ('OS_ECHEANCE', 'Échéance OS approchante'), ('VALIDATION_ATTACHEMENT', 'Validation attachement requise'), ('ETAPE_VALIDEE', 'Étape de validation terminée'), ('DOCUMENT_A_SIGNER', 'Document à signer'), ('FICHIER_MODIFIE', 'Fichier modifié'), ('FICHIER_SUPPRIME', 'Fichier supprimé'), ('NOUVEL_UTILISATEUR', 'Nouvel utilisateur ajouté'), ('ROLE_MODIFIE', 'Rôle modifié'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'prioritaire'], name='projets_not_utilisa_04f43a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expire_le'], name='projets_not_expire__55819e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification'], name='projets_not_type_no_0dc683_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['objet_type', 'objet_id'], name='projets_not_objet_t_ceaa58_idx'),
        ),
    ]
