# Generated by Django 5.2.5 on 2025-12-01 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0030_amelioration_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='processvalidation',
            name='tache_associee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_associee', to='projets.tache', verbose_name='Tâche associée'),
        ),
    ]
