# Generated by Django 5.2.5 on 2025-12-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0032_Add_Tche_Notification_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOUVELLE_TACHE', 'Nouvelle tâche créée'), ('TACHE_ASSIGNEE', 'Tâche assignée'), ('TACHE_MODIFIEE', 'Tâche modifiée'), ('TACHE_TERMINEE', 'Tâche terminée'), ('TACHE_URGENTE', 'Tâche devenue urgente'), ('TACHE_ECHEANCE', 'Échéance tâche approchante'), ('TACHE_EN_RETARD', 'Tâche en retard'), ('RETARD', 'Projet en retard'), ('NOUVEAU_AO', "Nouvel appel d'offres"), ('RECEPTION', 'Réception validée'), ('REUNION', 'Rendez-vous'), ('ECHEANCE', 'Échéance approchante'), ('PROJET_TERMINE', 'Projet terminé'), ('PROJET_ANNULE', 'Projet annulé'), ('PROJET_SUSPENDU', 'Projet suspendu'), ('PROJET_REOUVERT', 'Projet reouvert'), ('PROJET_MODIFIE', 'Projet modifié'), ('PROJET_EN_ARRET', 'Projet en arret'), ('NOUVEAU_PROJET', 'Nouveau projet'), ('ATTACHEMENT_BROUILLON', 'Attachement en cours de travail'), ('ATTACHEMENT_TRANSMIS', 'Attachement transmis'), ('ATTACHEMENT_MODIFIE', 'Attachement modifié'), ('ATTACHEMENT_SUPPRIME', 'Attachement supprimé'), ('ATTACHEMENT_VALIDE', 'Attachement validé'), ('ATTACHEMENT_REFUSE', 'Attachement refusé'), ('NOUVEL_ATTACHEMENT', 'Nouvel attachement créé'), ('ATTACHEMENT_SIGNE', 'Attachement en attente'), ('OS_NOTIFIE', 'Ordre de service notifié'), ('OS_ANNULE', 'Ordre de service annulé'), ('OS_ECHEANCE', 'Échéance OS approchante'), ('VALIDATION_ATTACHEMENT', 'Validation attachement requise'), ('ETAPE_VALIDEE', 'Étape de validation terminée'), ('DOCUMENT_A_SIGNER', 'Document à signer'), ('FICHIER_MODIFIE', 'Fichier modifié'), ('FICHIER_SUPPRIME', 'Fichier supprimé'), ('NOUVEL_UTILISATEUR', 'Nouvel utilisateur ajouté'), ('ROLE_MODIFIE', 'Rôle modifié'), ('AUTRE', 'Autre')], max_length=30),
        ),
    ]
