# Generated by Django 5.2.5 on 2025-12-08 20:26

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0034_profile_tel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BT01', 'BT01 - Bâtiment gros œuvre'), ('BT02', 'BT02 - Bâtiment second œuvre'), ('BT03', 'BT03 - Bâtiment équipements'), ('TP01', 'TP01 - Travaux publics terrassement'), ('TP02', 'TP02 - Travaux publics chaussées'), ('TP03', "TP03 - Travaux publics ouvrages d'art"), ('MT01', 'MT01 - Métallerie'), ('EL01', 'EL01 - Électricité'), ('PL01', 'PL01 - Plomberie'), ('AC01', 'AC01 - Acier'), ('CM01', 'CM01 - Ciment'), ('BO01', 'BO01 - Bois'), ('GL01', 'GL01 - Verre'), ('PE01', 'PE01 - Peinture'), ('MA01', "MA01 - Main d'œuvre")], max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('unite', models.CharField(help_text='Unité de mesure (Tonne, m3, Heure, etc.)', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddfqmth4q/image/upload/v1764860471/default_qu1agn.png', max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='ConfigRevisionProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_marche', models.CharField(choices=[('BATIMENT', 'Bâtiment'), ('TRAVAUX_PUBLICS', 'Travaux Publics'), ('METALLERIE', 'Métallerie'), ('ELECTRICITE', 'Électricité'), ('PLOMBERIE', 'Plomberie'), ('MULTI', "Multi-corps d'état")], max_length=50)),
                ('date_base', models.DateField(help_text='Date de référence pour les indices de base')),
                ('date_dernier_ajustement', models.DateField(blank=True, null=True)),
                ('taux_TVA', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('coefficient_K', models.DecimalField(decimal_places=3, default=0.85, help_text='Coefficient de stabilité (0 ≤ K ≤ 1)', max_digits=5)),
                ('marge_variation', models.DecimalField(decimal_places=2, default=5.0, help_text='Seuil de variation (%) déclenchant la révision', max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('coefficients', models.JSONField(default=dict, help_text="Dict {code_indice: coefficient} ex: {'BT01': 0.15, 'MA01': 0.25}")),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_revision', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Configuration révision de prix',
                'verbose_name_plural': 'Configurations révision de prix',
            },
        ),
        migrations.CreateModel(
            name='RevisionPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('date_revision', models.DateField(help_text='Date de la situation concernée')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('montant_HT_revisable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_HT_non_revisable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_revision_calcule', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('montant_revision_calcule', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_revision_valide', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('montant_revision_valide', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ajustement_taux', models.DecimalField(decimal_places=4, default=0, help_text='Ajustement manuel du taux (%)', max_digits=8)),
                ('motif_ajustement', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CALCULE', 'Calculé automatiquement'), ('MODIFIE', 'Modifié manuellement'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('detail_calcul', models.JSONField(default=dict, help_text='Détails des indices utilisés et calculs intermédiaires')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projets.configrevisionprojet')),
                ('decompte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_prix', to='projets.decompte')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Révision de prix',
                'verbose_name_plural': 'Révisions de prix',
                'ordering': ['-date_revision'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CALCUL', 'Calcul automatique'), ('MODIF_TX', 'Modification taux'), ('MODIF_MNT', 'Modification montant'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet')], max_length=50)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='projets.revisionprix')),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ValeurIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois')),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(default='Bulletin Officiel', max_length=200)),
                ('date_publication', models.DateField()),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='projets.indicerevision')),
            ],
            options={
                'ordering': ['indice', 'mois'],
                'unique_together': {('indice', 'mois')},
            },
        ),
    ]
