# Generated by Django 5.2.5 on 2025-12-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0035_indicerevision_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionprix',
            name='config',
        ),
        migrations.RemoveField(
            model_name='historiquerevision',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='historiquerevision',
            name='utilisateur',
        ),
        # migrations.RemoveField(
        #     model_name='valeurindice',
        #     name='indice',
        # ),
        migrations.RemoveField(
            model_name='revisionprix',
            name='decompte',
        ),
        migrations.RemoveField(
            model_name='revisionprix',
            name='valide_par',
        ),
        migrations.AlterUniqueTogether(
            name='valeurindice',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='decompte',
            name='montant_revision_prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Révision des prix'),
        ),
        migrations.DeleteModel(
            name='ConfigRevisionProjet',
        ),
        migrations.DeleteModel(
            name='HistoriqueRevision',
        ),
        migrations.DeleteModel(
            name='IndiceRevision',
        ),
        migrations.DeleteModel(
            name='ValeurIndice',
        ),
        migrations.DeleteModel(
            name='RevisionPrix',
        ),
    ]
