# Generated by Django 5.2.5 on 2026-08-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0037_dossier_alter_documentadministratif_type_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentadministratif',
            name='type_document',
            field=models.CharField(blank=True, choices=[('', 'Sélectionner un type...'), ('Attestation', 'Attestation'), ("Attestation d'enregistrement", "Attestation d'enregistrement"), ('Attestation de conformité', 'Attestation de conformité'), ("Attestation d'assurance", "Attestation d'assurance"), ('Assurance', 'Assurance'), ('Caution provisoire', 'Caution provisoire'), ('Caution définitive', 'Caution définitive'), ('Bon de commande', 'Bon de commande'), ('CPS', 'Cahier des prescriptions spéciales (CPS)'), ('CPS avenant', "CPS d'avenant"), ('Cahier des charges', 'Cahier des charges (CDC)'), ('Contrat', 'Contrat'), ('Contrat de sous-traitance', 'Contrat de sous-traitance'), ('Cahier des clauses techniques', 'Cahier des clauses techniques (CCT)'), ('CCTP', 'Cahier des clauses techniques particulières (CCTP)'), ('CCAP', 'Cahier des clauses administratives particulières (CCAP)'), ('Cahier des clauses administratives', 'Cahier des clauses administratives (CCA)'), ('BDP', 'Bordereau des prix (BDP)'), ('Contrat de garantie', 'Contrat de garantie'), ('Convention', 'Convention'), ('Autorisation', 'Autorisation'), ('Rapport', 'Rapport'), ('Procès-verbal', 'Procès-verbal (PV)'), ('Autre', 'Autre')], default='', max_length=100, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='suiviexecution',
            name='type_suivi',
            field=models.CharField(choices=[('reunion', 'Réunion de chantier'), ('incident', 'Incident'), ('planning', 'Mise à jour planning'), ('livraison', 'Livraison'), ('validation', "Validation d'étape"), ('courrier', 'Courrier'), ('autre', 'Autre')], max_length=100, verbose_name='Type'),
        ),
    ]
