# Generated by Django 5.2.5 on 2026-08-22 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0039_dossier_gerant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='utilisateurs',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs du dossier'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('GERANT', 'Gérant'), ('STAFF', 'Staff'), ('UTILISATEUR', 'Utilisateur')], default='UTILISATEUR', max_length=20),
        ),
    ]
