# Generated by Django 5.2.5 on 2026-08-26 10:00

import projets.models.projet
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0040_dossier_utilisateurs_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentadministratif',
            name='fichier',
            field=models.FileField(upload_to=projets.models.projet.document_upload_path, verbose_name='Fichier'),
        ),
    ]
