# Generated by Django 5.2.5 on 2026-08-26 10:18

import projets.models.projet
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0041_alter_documentadministratif_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='attachements/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='fichiersuivi',
            name='fichier',
            field=models.FileField(upload_to=projets.models.projet.FichierSuivi.upload_path, verbose_name='Fichier'),
        ),
    ]
