# Generated by Django 5.2.5 on 2026-08-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0042_alter_attachement_fichier_alter_fichiersuivi_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapevalidation',
            name='fichier',
            field=models.FileField(blank=True, db_column='fichier_validation', null=True, upload_to='validations_attachements_etapes/%Y/%m/', verbose_name='Fichier de validation'),
        ),
        migrations.AlterField(
            model_name='ordreservice',
            name='fichier',
            field=models.FileField(blank=True, db_column='documents', null=True, upload_to='ordres_services/'),
        ),
        migrations.AlterField(
            model_name='processvalidation',
            name='fichier',
            field=models.FileField(blank=True, db_column='fichier_validation', null=True, upload_to='validations_attachements/%Y/%m/', verbose_name='Fichier de validation'),
        ),
    ]
