# Generated by Django 5.2.5 on 2026-08-26 10:47

import projets.models.profile
from django.db import migrations, models


def replace_legacy_cloudinary_avatars(apps, schema_editor):
    Profile = apps.get_model('projets', 'Profile')
    Profile.objects.filter(avatar__startswith='http').update(avatar='avatars/default.png')


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0043_alter_etapevalidation_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to=projets.models.profile.avatar_upload_path),
        ),
        migrations.RunPython(replace_legacy_cloudinary_avatars, migrations.RunPython.noop),
    ]
