# Generated by Django 5.2.5 on 2026-08-26 11:28

import projets.models.profile
from django.db import migrations, models


def replace_legacy_default_avatar(apps, schema_editor):
    Profile = apps.get_model('projets', 'Profile')
    Profile.objects.filter(avatar='avatars/default.png').update(
        avatar='avatars/default.jpeg'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0044_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpeg', upload_to=projets.models.profile.avatar_upload_path),
        ),
        migrations.RunPython(replace_legacy_default_avatar, migrations.RunPython.noop),
    ]
