# Generated by Django 5.2.5 on 2026-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0045_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='activite',
            field=models.CharField(choices=[('TRAVAUX', 'Travaux'), ('FOURNITURES', 'Fournitures'), ('SERVICES', 'Services')], default='TRAVAUX', max_length=20, verbose_name='Activité'),
        ),
    ]
