# Generated by Django 5.2.5 on 2026-08-26 21:06

import django.db.models.deletion
import projets.models.suivi_projet
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0046_dossier_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('meteo', models.CharField(blank=True, max_length=100, verbose_name='Météo')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température')),
                ('travaux_realises', models.TextField(blank=True, verbose_name='Travaux réalisés')),
                ('evenements', models.TextField(blank=True, verbose_name='Événements')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('redacteur', models.CharField(blank=True, max_length=150, verbose_name='Rédacteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_journaliers', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
            bases=(projets.models.suivi_projet.ActiviteTravauxMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DepenseRapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('MATERIEL', 'Matériel'), ('LOCATION', 'Location'), ('SOUS_TRAITANCE', 'Sous-traitance'), ('FOURNITURE', 'Fourniture'), ('TRANSPORT', 'Transport'), ('CONSOMMABLE', 'Consommable')], max_length=30)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='projets.rapportjournalier', verbose_name='Rapport journalier')),
            ],
            options={
                'ordering': ['categorie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SituationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name="Chiffre d'affaires")),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations_mensuelles', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'ordering': ['-annee', '-mois', '-id'],
            },
            bases=(projets.models.suivi_projet.ActiviteTravauxMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DepenseSituationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('MATERIEL', 'Matériel'), ('LOCATION', 'Location'), ('SOUS_TRAITANCE', 'Sous-traitance'), ('FOURNITURE', 'Fourniture'), ('TRANSPORT', 'Transport'), ('CONSOMMABLE', 'Consommable')], max_length=30)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='projets.situationmensuelle', verbose_name='Situation mensuelle')),
            ],
            options={
                'ordering': ['categorie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockRapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='Unité')),
                ('quantite_entree', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('quantite_sortie', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('stock_restant', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='projets.rapportjournalier', verbose_name='Rapport journalier')),
            ],
            options={
                'ordering': ['designation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockSituationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='Unité')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valeur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='projets.situationmensuelle', verbose_name='Situation mensuelle')),
            ],
            options={
                'ordering': ['designation', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rapportjournalier',
            constraint=models.UniqueConstraint(fields=('projet', 'date'), name='unique_rapport_journalier_projet_date'),
        ),
        migrations.AddConstraint(
            model_name='situationmensuelle',
            constraint=models.UniqueConstraint(fields=('projet', 'annee', 'mois'), name='unique_situation_mensuelle_projet_periode'),
        ),
    ]
