# Generated by Django 5.2.5 on 2026-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0047_rapportjournalier_depenserapportjournalier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenserapportjournalier',
            name='unite',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unité'),
        ),
    ]
