# Generated by Django 5.2.5 on 2026-08-27 13:46

from decimal import Decimal
from django.db import migrations, models


def calculer_montants_existants(apps, schema_editor):
    DepenseRapportJournalier = apps.get_model('projets', 'DepenseRapportJournalier')
    for depense in DepenseRapportJournalier.objects.all():
        depense.montant = (depense.quantite or Decimal('0.000')) * (depense.prix_unitaire or Decimal('0.00'))
        depense.save(update_fields=['montant'])


def revenir_montant_en_prix_unitaire(apps, schema_editor):
    # Rien à faire : la colonne "montant" (prix_unitaire) n'est pas modifiée par ce recalcul
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0048_depenserapportjournalier_unite'),
    ]

    operations = [
        # Renomme le champ Python "montant" -> "prix_unitaire" en conservant la même colonne
        # physique ("montant") : aucune donnée existante n'est perdue ni altérée.
        migrations.RenameField(
            model_name='depenserapportjournalier',
            old_name='montant',
            new_name='prix_unitaire',
        ),
        migrations.AlterField(
            model_name='depenserapportjournalier',
            name='prix_unitaire',
            field=models.DecimalField(db_column='montant', decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix unitaire'),
        ),
        # Nouveau champ "montant" (total = quantité x prix unitaire), sur une nouvelle colonne.
        migrations.AddField(
            model_name='depenserapportjournalier',
            name='montant',
            field=models.DecimalField(db_column='montant_total', decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Montant'),
        ),
        migrations.RunPython(calculer_montants_existants, revenir_montant_en_prix_unitaire),
    ]
