# Generated by Django 5.2.5 on 2026-08-27 14:55

import projets.models.suivi_projet
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0049_depenserapportjournalier_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournalier',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=projets.models.suivi_projet.rapport_journalier_document_upload_path, verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
    ]
