# Generated by Django 5.2.5 on 2026-08-28 20:59

import projets.models.suivi_projet
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0050_rapportjournalier_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationmensuelle',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=projets.models.suivi_projet.situation_mensuelle_document_upload_path, verbose_name='Document mensuel'),
        ),
        migrations.AddField(
            model_name='situationmensuelle',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de fichier original'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOUVELLE_TACHE', 'Nouvelle tâche créée'), ('TACHE_ASSIGNEE', 'Tâche assignée'), ('TACHE_MODIFIEE', 'Tâche modifiée'), ('TACHE_TERMINEE', 'Tâche terminée'), ('TACHE_URGENTE', 'Tâche devenue urgente'), ('TACHE_ECHEANCE', 'Échéance tâche approchante'), ('TACHE_EN_RETARD', 'Tâche en retard'), ('RETARD', 'Projet en retard'), ('NOUVEAU_AO', "Nouvel appel d'offres"), ('RECEPTION', 'Réception validée'), ('REUNION', 'Rendez-vous'), ('ECHEANCE', 'Échéance approchante'), ('PROJET_TERMINE', 'Projet terminé'), ('PROJET_ANNULE', 'Projet annulé'), ('PROJET_SUSPENDU', 'Projet suspendu'), ('PROJET_REOUVERT', 'Projet reouvert'), ('PROJET_MODIFIE', 'Projet modifié'), ('PROJET_EN_ARRET', 'Projet en arret'), ('NOUVEAU_PROJET', 'Nouveau projet'), ('NOUVEAU_RAPPORT_JOURNALIER', 'Nouveau rapport journalier'), ('RAPPORT_JOURNALIER_MODIFIE', 'Rapport journalier modifié'), ('NOUVELLE_SITUATION_MENSUELLE', 'Nouvelle situation mensuelle'), ('SITUATION_MENSUELLE_MODIFIEE', 'Situation mensuelle modifiée'), ('ATTACHEMENT_BROUILLON', 'Attachement en cours de travail'), ('ATTACHEMENT_TRANSMIS', 'Attachement transmis'), ('ATTACHEMENT_MODIFIE', 'Attachement modifié'), ('ATTACHEMENT_SUPPRIME', 'Attachement supprimé'), ('ATTACHEMENT_VALIDE', 'Attachement validé'), ('ATTACHEMENT_REFUSE', 'Attachement refusé'), ('NOUVEL_ATTACHEMENT', 'Nouvel attachement créé'), ('ATTACHEMENT_SIGNE', 'Attachement en attente'), ('OS_NOTIFIE', 'Ordre de service notifié'), ('OS_ANNULE', 'Ordre de service annulé'), ('OS_ECHEANCE', 'Échéance OS approchante'), ('VALIDATION_ATTACHEMENT', 'Validation attachement requise'), ('ETAPE_VALIDEE', 'Étape de validation terminée'), ('DOCUMENT_A_SIGNER', 'Document à signer'), ('FICHIER_MODIFIE', 'Fichier modifié'), ('FICHIER_SUPPRIME', 'Fichier supprimé'), ('NOUVEL_UTILISATEUR', 'Nouvel utilisateur ajouté'), ('ROLE_MODIFIE', 'Rôle modifié'), ('AUTRE', 'Autre')], max_length=30),
        ),
    ]
