# Generated by Django 5.2.5 on 2026-08-28 21:34

import django.db.models.deletion
import projets.models.suivi_projet
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0051_situationmensuelle_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationmensuelle',
            name='document',
        ),
        migrations.RemoveField(
            model_name='situationmensuelle',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='situationmensuelle',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='situationmensuelle',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.CreateModel(
            name='DocumentSituationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=projets.models.suivi_projet.situation_mensuelle_document_upload_path, verbose_name='Document')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projets.situationmensuelle', verbose_name='Situation mensuelle')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
