# Generated by Django 5.2.5 on 2026-08-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0052_remove_situationmensuelle_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsituationmensuelle',
            name='checksum',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='documentsituationmensuelle',
            constraint=models.UniqueConstraint(condition=models.Q(('checksum', ''), _negated=True), fields=('situation', 'checksum'), name='unique_situation_document_checksum'),
        ),
    ]
