# Generated by Django 5.2.5 on 2026-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0055_profile_role_chef_projet_normalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotprojet',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0 = lot hors TVA. Laisser vide pour utiliser le taux du projet.', max_digits=5, null=True, verbose_name='Taux de TVA (%)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Utilisé comme repli par les lots dont le taux de TVA n'est pas renseigné.", max_digits=5, null=True, verbose_name='Taux de TVA par défaut (%)'),
        ),
    ]
