# Generated by Django 5.2.5 on 2026-08-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0056_lot_projet_taux_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('type_materiel', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('immatriculation', models.CharField(blank=True, max_length=50, verbose_name='Immatriculation / N° de série')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériel',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CHEF_PROJET', 'Chef de projet'), ('GERANT', 'Chef de projet (historique)'), ('CHEF_CHANTIER', 'Chef de chantier'), ('POINTEUR', 'Pointeur'), ('STAFF', 'Staff'), ('UTILISATEUR', 'Utilisateur')], default='UTILISATEUR', max_length=20),
        ),
    ]
