# Generated by Django 5.2.5 on 2026-08-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0057_personnel_materiel_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('type_consommable', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('fournisseur', models.CharField(blank=True, max_length=50, verbose_name='Fournisseur')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DH)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Consommable',
                'verbose_name_plural': 'Consommables',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Fourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('type_fourniture', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('fournisseur', models.CharField(blank=True, max_length=50, verbose_name='Fournisseur')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DH)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fourniture',
                'verbose_name_plural': 'Fournitures',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('type_materiel', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('locataire', models.CharField(blank=True, max_length=50, verbose_name='Locataire')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DH)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='SousTraitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('type_sous_traitance', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('prestataire', models.CharField(blank=True, max_length=50, verbose_name='Prestataire')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DH)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Sous-traitance',
                'verbose_name_plural': 'Sous-traitances',
                'ordering': ['designation'],
            },
        ),
        migrations.AddField(
            model_name='materiel',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DH)'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='unite',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='unite',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unité'),
        ),
    ]
