# Generated by Django 5.2.5 on 2026-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0059_seed_types_ordre_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('type_transport', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('transporteur', models.CharField(blank=True, max_length=50, verbose_name='Transporteur')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (DH)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['designation'],
            },
        ),
    ]
