# Generated by Django 5.2.5 on 2026-09-07

from django.db import migrations, models


def create_revenue_lines(apps, schema_editor):
    SituationMensuelle = apps.get_model('projets', 'SituationMensuelle')
    RecetteSituationMensuelle = apps.get_model('projets', 'RecetteSituationMensuelle')
    for situation in SituationMensuelle.objects.all():
        RecetteSituationMensuelle.objects.create(
            situation=situation,
            rubrique='TRAVAUX_REALISES',
            montant=situation.chiffre_affaires,
        )
        for rubrique in ['REVISION_PRIX', 'REFACTURATION_EXTERNE']:
            RecetteSituationMensuelle.objects.create(
                situation=situation,
                rubrique=rubrique,
                montant=0,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0060_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetteSituationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(choices=[('TRAVAUX_REALISES', 'Travaux réalisés'), ('REVISION_PRIX', 'Révision des prix'), ('REFACTURATION_EXTERNE', 'Refacturation externe')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('situation', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='recettes', to='projets.situationmensuelle', verbose_name='Situation mensuelle')),
            ],
            options={
                'ordering': ['rubrique', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recettesituationmensuelle',
            constraint=models.UniqueConstraint(fields=('situation', 'rubrique'), name='unique_recette_situation_rubrique'),
        ),
        migrations.RunPython(create_revenue_lines, migrations.RunPython.noop),
    ]