# Generated by Django 5.2.5 on 2026-09-07

from django.db import migrations, models


def backfill_expense_totals(apps, schema_editor):
    DepenseSituationMensuelle = apps.get_model('projets', 'DepenseSituationMensuelle')
    for depense in DepenseSituationMensuelle.objects.all():
        depense.montant = depense.montant_base
        depense.save(update_fields=['montant'])


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0061_recettesituationmensuelle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depensesituationmensuelle',
            old_name='montant',
            new_name='montant_base',
        ),
        migrations.AlterField(
            model_name='depensesituationmensuelle',
            name='montant_base',
            field=models.DecimalField(db_column='montant', decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='depensesituationmensuelle',
            name='cession_entrante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='depensesituationmensuelle',
            name='cession_sortante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='depensesituationmensuelle',
            name='montant',
            field=models.DecimalField(db_column='montant_total', decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.RunPython(backfill_expense_totals, migrations.RunPython.noop),
    ]