# Generated by Django 5.2.5 on 2026-09-09 09:06

from django.db import migrations, models


def creer_categories_charge(apps, schema_editor):
    CategorieCharge = apps.get_model('projets', 'CategorieCharge')
    categories = [
        ('PERSONNEL', 'Personnel'),
        ('MATERIEL', 'Matériel'),
        ('LOCATION', 'Location'),
        ('SOUS_TRAITANCE', 'Sous-traitance'),
        ('FOURNITURE', 'Fourniture'),
        ('TRANSPORT', 'Transport'),
        ('CONSOMMABLE', 'Consommable'),
    ]
    CategorieCharge.objects.bulk_create([
        CategorieCharge(code=code, nom=nom, ordre=ordre)
        for ordre, (code, nom) in enumerate(categories, start=1)
    ])


def supprimer_categories_charge(apps, schema_editor):
    CategorieCharge = apps.get_model('projets', 'CategorieCharge')
    CategorieCharge.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0062_depenserapportmensuelle_cessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie de charge',
                'verbose_name_plural': 'Catégories de charges',
                'ordering': ['ordre', 'nom', 'id'],
            },
        ),
        migrations.RunPython(creer_categories_charge, supprimer_categories_charge),
    ]
