# Generated by Django 5.2.5 on 2026-09-09 09:12

import django.db.models.deletion
from django.db import migrations, models


def rattacher_anciennes_categories(apps, schema_editor):
    CategorieCharge = apps.get_model('projets', 'CategorieCharge')
    modeles_depenses = [
        apps.get_model('projets', 'DepenseRapportJournalier'),
        apps.get_model('projets', 'DepenseSituationMensuelle'),
    ]
    categories = {
        categorie.code: categorie
        for categorie in CategorieCharge.objects.all()
    }
    for modele in modeles_depenses:
        for code, categorie in categories.items():
            modele.objects.filter(categorie=code, categorie_charge__isnull=True).update(
                categorie_charge=categorie.pk
            )


def detacher_anciennes_categories(apps, schema_editor):
    for nom_modele in ('DepenseRapportJournalier', 'DepenseSituationMensuelle'):
        modele = apps.get_model('projets', nom_modele)
        modele.objects.update(categorie_charge=None)


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0063_categorie_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenserapportjournalier',
            name='categorie_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_rapports_journaliers', to='projets.categoriecharge', verbose_name='Catégorie de charge'),
        ),
        migrations.AddField(
            model_name='depensesituationmensuelle',
            name='categorie_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_situations_mensuelles', to='projets.categoriecharge', verbose_name='Catégorie de charge'),
        ),
        migrations.RunPython(rattacher_anciennes_categories, detacher_anciennes_categories),
    ]
