# Generated by Django 5.2.5 on 2026-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0064_categories_charge_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenserapportjournalier',
            name='categorie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='depensesituationmensuelle',
            name='categorie',
            field=models.CharField(max_length=30),
        ),
    ]
