# Generated by Django 5.2.5 on 2026-09-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0066_projet_unite_delai'),
    ]

    operations = [
        # ------------------------------------------------------------------
        # 1. Nouveaux modèles de référence
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='TypeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Désignation')),
                ('icone', models.CharField(blank=True, help_text='Nom du fichier situé dans static/images/materiels/', max_length=120, verbose_name='Icône')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de matériel',
                'verbose_name_plural': 'Types de matériel',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Atelier',
                'verbose_name_plural': 'Ateliers',
                'ordering': ['code'],
            },
        ),

        # ------------------------------------------------------------------
        # 2. Location : reste un CharField (aucun risque de cast)
        # ------------------------------------------------------------------
        migrations.AlterField(
            model_name='location',
            name='type_materiel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de matériel'),
        ),

        # ------------------------------------------------------------------
        # 3. Materiel : CharField -> ForeignKey
        #    Passage par un nom intermédiaire : sous SQLite, un RemoveField
        #    suivi d'un AddField de même nom fait recopier l'ancienne valeur
        #    texte dans la nouvelle colonne FK (IntegrityError).
        #    Les anciens libellés sont perdus (écrasement accepté).
        # ------------------------------------------------------------------
        migrations.RenameField(
            model_name='materiel',
            old_name='type_materiel',
            new_name='type_materiel_ancien',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='type_materiel_ancien',
        ),
        migrations.AddField(
            model_name='materiel',
            name='type_materiel',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='materiels',
                to='projets.typemateriel',
                verbose_name='Type de matériel',
            ),
        ),

        # ------------------------------------------------------------------
        # 4. Affectation des ressources aux ateliers
        # ------------------------------------------------------------------
        migrations.CreateModel(
            name='AffectationRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
                ('atelier', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='affectations',
                    to='projets.atelier',
                    verbose_name='Atelier',
                )),
                ('materiel', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='affectations',
                    to='projets.materiel',
                    verbose_name='Matériel',
                )),
            ],
            options={
                'verbose_name': 'Affectation de ressource',
                'verbose_name_plural': 'Affectations de ressources',
                'ordering': ['-date_debut'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('atelier', 'materiel', 'date_debut'),
                        name='unique_affectation_materiel_atelier_date',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('date_fin__isnull', True),
                            ('date_fin__gte', models.F('date_debut')),
                            _connector='OR',
                        ),
                        name='affectation_dates_coherentes',
                    ),
                ],
            },
        ),
    ]