# Generated by Django 5.2.5 on 2026-09-22 09:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0068_seed_types_materiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('MARCHE', 'En marche'), ('ARRET', "À l'arrêt"), ('PANNE', 'En panne'), ('MAINTENANCE', 'En maintenance'), ('DISPONIBLE', 'Disponible')], max_length=20, verbose_name='État')),
                ('localisation', models.CharField(blank=True, max_length=150, verbose_name='Localisation')),
                ('heures', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Heures')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Relevé matériel',
                'verbose_name_plural': 'Relevés matériel',
                'ordering': ['materiel__designation', 'etat', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='atelier',
            options={'ordering': ['projet', 'code'], 'verbose_name': 'Atelier', 'verbose_name_plural': 'Ateliers'},
        ),
        migrations.AddField(
            model_name='atelier',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ateliers', to='projets.projet', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AddConstraint(
            model_name='atelier',
            constraint=models.UniqueConstraint(fields=('projet', 'code'), name='unique_atelier_projet_code'),
        ),
        migrations.AddField(
            model_name='relevemateriel',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves', to='projets.atelier', verbose_name='Atelier'),
        ),
        migrations.AddField(
            model_name='relevemateriel',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releves', to='projets.materiel', verbose_name='Matériel'),
        ),
        migrations.AddField(
            model_name='relevemateriel',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_materiel', to='projets.rapportjournalier', verbose_name='Rapport journalier'),
        ),
        migrations.AddConstraint(
            model_name='relevemateriel',
            constraint=models.CheckConstraint(condition=models.Q(('heures__gte', 0), ('heures__lte', 24)), name='releve_materiel_heures_valides'),
        ),
    ]
