# Generated by Django 5.2.5 on 2026-10-03 20:56

import projets.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0069_atelier_projet_releve_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de parc'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=projets.models.profile.avatar_upload_path),
        ),
    ]
