# Generated by Django 5.2.5 on 2026-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0070_alter_materiel_immatriculation_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liste_projets_vue',
            field=models.CharField(choices=[('tableau', 'Tableau'), ('cartes', 'Cartes')], default='tableau', max_length=10, verbose_name='Vue des projets préférée'),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Sombre'), ('light', 'Clair'), ('system', 'Système')], default='dark', max_length=10, verbose_name='Thème préféré'),
        ),
    ]
