# Generated by Django 5.2.5 on 2026-10-04 23:46

from django.db import migrations

def clean_action_urls(apps, schema_editor):
    """Nettoie les action_url cassés dans les notifications."""
    Notification = apps.get_model('projets', 'Notification')
    
    # Vider les URLs cassées pour tous les types
    updated = Notification.objects.filter(
        objet_type__in=['tache', 'projet', 'ordre_service']
    ).update(action_url='')
    
    print(f"  → {updated} notifications nettoyées")


def reverse_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0071_profile_liste_projets_vue_profile_theme'),
    ]

    operations = [
        migrations.RunPython(clean_action_urls, reverse_noop),
    ]
