# Generated by Django 5.2.5 on 2026-10-05 12:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0072_clean_notification_action_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachement',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant HT'),
        ),
    ]
